### ISSUE TITLE
0.7.2 Release detected as trojan by windows defender

### ISSUE THREAD

**Issue by zacharyluck** [Steamopollys/Steamodded#31]
both steamodded_injector.exe and steamodded_PS_injector.exe are blocked by Windows Defender.

steamodded_injector listed as Trojan:Win32/Acll,
steamodded_PS_injector listed as Trojan:Win32/Wacatac.B!ml

I was linked to this github from a youtube video; he seems to be downloading these files two days earlier just fine, only blocked by the "don't trust unsigned programs" thing windows usually pops up. [Link to that video](https://www.youtube.com/watch?v=LSwLx3h_a4o)

I'm assuming this repo isn't intended to be a virus, otherwise it wouldn't be used by so many mods, and [linked in a guide to find and download balatro mods,](https://github.com/jie65535/awesome-balatro?tab=readme-ov-file#mod-loaders) so I just wanted to let you guys know.

**Comment by atlasveldine** [comment]
Usually, I wouldn't bother replying to something like this, but if someone else runs into this issue and checks this repo's Issue list, they may see this issue and decide against using Steamodded, which would be a damn shame.

Anytime Windows Defender (or Chrome, or any other anti-malware app baked into places they don't belong, for that matter) reports a file as a virus, I advise that you first take a breath and second question it. Normally, I'd recommend you "trust but verify" - in this case, however, it's more like, "distrust _and_ verify." Many of the "big" anti-malware apps these days have thus lovely habit of reporting that completely legitimate software are malware. Part of the reason why is because they often heavily rely on extremely flawed black-box _(or, at least, partially black-box)_ AI malware detection algorithms. Another is that any so-called "hacking tool" gets labeled as malware regardless of whether or not it even _is_ a tool for hacking _(not to mention, regardless of whether if's genuinely malicious)_.

Antivirus software such as `Microsoft Defender`, `Norton`, `McAfee`, as well as the vast majority of commonplace antimalware services, are pretty well-known for being[^1] _(trash, and, also, being)_ overzealous when it comes to actually detecting genuine malicious files. `Chrome` has recently added itself to the list of software which makes it infuriatingly difficult[^2] to bypass or disable their built-in virus scanning garbage[^3]. 
[^1]: > 
Trash. Extremely massive, unnecessarily bulky, obnoxious, irritating useless money-hungry _garbage_.
[^2]: > `Chrome` has recently added itself to the list of software which makes it infuriatingly difficult[^2] to bypass or disable their built-in virus scanning garbage[^3]. at least, without jumping through a ton of ridiculous hoops & losing functionality
[^3]: though, `Chrome` is nowhere near as bad as `Windows Defender`
For example, I have Windows Defender turned off completely in every way - or, at least, in every way I was able to figure out on my own without explicitly researching to figure out if there's some arcane method of disabling it - **and _yet_**, Windows' defective definitely-not-a-Defender is so indefensibly over-defensive that, despite the great lengths I went through to disable it, it _still, **somehow_** managed to remove `steamodded_injector.exe` the moment the download finished. Bizarrely, the **PowerShell** binary and script variants both download without complaint - despite Malwarebytes _**correctly**_ identifying the binary, `steamodded_PS_injector.exe`, as **Generic.Malware/Suspicious** - an identifier that 
[Malwarebytes defines as](https://www.malwarebytes.com/blog/detections/generic)
https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Acll&threatid=2147900036

**[`VirusTotal`](https://www.virustotal.com/gui/url/31242ef6451e907aa33f8b399ab7375f16f7d89aed9ea1e1e6c531c7214fb6a9)** for _`steamodded_injector.exe`_, `v0.7.2`

**Comment by BarkalotDesigns** [comment]
Yeah, I'm experiencing the same thing, I tried downloading earlier versions but they all get detected as malware. Hopefully this gets resolved, I'm looking forward to try some mods.

**Comment by sh0nuff** [comment]
This is an ongoing issue where Windows labels this as a severe threat - even if you Allow the file in Windows Defender so it can be downloaded again, when you try to install it, there's a red popup marking the file as Malicious and sensitive personal data may be at risk, forcing users a second time to Ignore and run anyways.

If this is to be expected, it should be mentioned and clarified as safe in the installation instructions.. given that nothing of the sort is included I am still hesitant to install it in case some sort of redirect has occurred and it's not the correct file.

**Comment by Steamopollys** [comment]
Hello,

False Anti Virus flags for mod related project happen all the time at the start of development cycle. Windows tend to dislike unsigned binaries, specially the ones that change some other stuffs on you computer. It will be solved when it will be solved.

However, a non flagged installation option is already mentioned with Lovely. If you are not willing to manipulate your Anti Virus, please use this one. A more detailed tutorial on how to install Steamodded with Lovely will come soon, but the actual one will still do the job.
