### ISSUE TITLE
Occasional crashing on removal of decks.

### ISSUE THREAD

**Issue by spikeof2010** [Steamopollys/Steamodded#57]
Currently, if you load up a modded deck, select it, do a run, then close the game and remove said mod, the game will still try to default putting you at that deck on the new game screen, crashing the game, presumably because it is trying to load from a deck that doesn't exist. I think a good solution for this would be to simply have a fallback deck (blue deck) for the deck screen to default to each start up (which could be configurable, but otherwise not much of a hassle). Perhaps if it detects that the modlist it loaded is different from the last session, it also does this fallback feature.

**Comment by Steamopollys** [comment]
Hey, that could be an idea. The Game is more to blame than Steamodded for this one because of how the profiles works, that's sadly not the only error that can happen with profiles.

We will try to address the issue, but I doubt we will be able to cover every possible cases. This one seems reasonably easy to do and will use some other changes I'm planning to do.

**Comment by Aurelius7309** [comment]
The game already has a fallback, the loader just failed to use it up to now. A simple fix has been put in place for 0.9.6, we'll investigate further if parts of this issue stay unaddressed by it.
